# Generated by Django 5.0.3 on 2024-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_productvariant_store_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sale_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='store_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
